version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      STORAGE_PATH: 'data/database.json'
